//
//  GameInterfacePrefix.h
//  MAX
//
//  Created by  Developer on 07.04.13.
//  Copyright (c) 2013 AntonKatekov. All rights reserved.
//

#ifndef MAX_GameInterfacePrefix_h
#define MAX_GameInterfacePrefix_h

#define MAX_DEFAULT_FONT "HelveticaNeue-Bold"
#define MAX_COLOR_BLACK ccc3(0,0,0)



#define MAX_IMAGE_AIRUNITS_EMPTY "EI_AIR"
#define MAX_IMAGE_AMMO_EMPTY "EI_AMMO"
#define MAX_IMAGE_FUEL_EMPTY "EI_FUEL"
#define MAX_IMAGE_GOLD_EMPTY "EI_GOLD"
#define MAX_IMAGE_HITSB_EMPTY "EI_HITSB"
#define MAX_IMAGE_HITSR_EMPTY "EI_HITSR"
#define MAX_IMAGE_HITSY_EMPTY "EI_HITSY"
#define MAX_IMAGE_LANDUNITS_EMPTY "EI_LAND"
#define MAX_IMAGE_POWER_EMPTY "EI_POWER"
#define MAX_IMAGE_RAWMAT_EMPTY "EI_RAW"
#define MAX_IMAGE_SEAUNITS_EMPTY "EI_SEA"
#define MAX_IMAGE_SHOTS_EMPTY "EI_SHOTS"
#define MAX_IMAGE_SPEED_EMPTY "EI_SPEED"
#define MAX_IMAGE_WORKERS_EMPTY "EI_WORK"



#define MAX_IMAGE_AIRUNITS "SI_AIR"
#define MAX_IMAGE_AMMO "SI_AMMO"
#define MAX_IMAGE_FUEL "SI_FUEL"
#define MAX_IMAGE_GOLD "SI_GOLD"
#define MAX_IMAGE_HITSB "SI_HITSB"
#define MAX_IMAGE_HITSR "SI_HITSR"
#define MAX_IMAGE_HITSY "SI_HITSY"
#define MAX_IMAGE_LANDUNITS "SI_LAND"
#define MAX_IMAGE_POWER "SI_POWER"
#define MAX_IMAGE_RAWMAT "SI_RAW"
#define MAX_IMAGE_SEAUNITS "SI_SEA"
#define MAX_IMAGE_SHOTS "SI_SHOTS"
#define MAX_IMAGE_SPEED "SI_SPEED"
#define MAX_IMAGE_WORKERS "SI_WORK"



#define MAX_IMAGE_AMMO_INFO "I_AMMO"
#define MAX_IMAGE_ARMOR_INFO "I_ARMOR"
#define MAX_IMAGE_FUEL_INFO "I_FUEL"
#define MAX_IMAGE_GOLD_INFO "I_GOLD"
#define MAX_IMAGE_GOLDE_INFO "I_GOLDE"
#define MAX_IMAGE_HITS_INFO "I_HITS"
#define MAX_IMAGE_ATTACK_INFO "I_HRDATK"
#define MAX_IMAGE_LIFE_INFO "I_LIFE"
#define MAX_IMAGE_POWER_INFO "I_POWER"
#define MAX_IMAGE_RANGE_INFO "I_RANGE"
#define MAX_IMAGE_RAW_INFO "I_RAW"
#define MAX_IMAGE_RAWE_INFO "I_RAWE"
#define MAX_IMAGE_SCAN_INFO "I_SCAN"
#define MAX_IMAGE_SHOTS_INFO "I_SHOTS"
#define MAX_IMAGE_SPEED_INFO "I_SPEED"

#endif
