//
//  GIUnitActionMenu.cpp
//  MAX
//
//  Created by  Developer on 07.05.13.
//  Copyright (c) 2013 AntonKatekov. All rights reserved.
//

#include "GIUnitActionMenu.h"
#include <vector>
#include "miniPrefix.h"

#define BUTTON_UNIT_MENU_ACTION_ACTIVATE    "ACTVT"
#define BUTTON_UNIT_MENU_ACTION_ALLOCATE    "ALLOC"
#define BUTTON_UNIT_MENU_ACTION_ATTACK      "ATTK"
#define BUTTON_UNIT_MENU_ACTION_BUILD       "BUILD"
#define BUTTON_UNIT_MENU_ACTION_BUYUPGRADES "BYUPG"
#define BUTTON_UNIT_MENU_ACTION_CLEAR       "CLEAR"
#define BUTTON_UNIT_MENU_ACTION_DISABLE     "DISBL"
#define BUTTON_UNIT_MENU_ACTION_DONE        "DONE"
#define BUTTON_UNIT_MENU_ACTION_ENTER       "ENTER"
#define BUTTON_UNIT_MENU_ACTION_FOLLOW      "FLLOW"
#define BUTTON_UNIT_MENU_ACTION_LOAD        "LOAD"
#define BUTTON_UNIT_MENU_ACTION_PLACE       "PLACE"
#define BUTTON_UNIT_MENU_ACTION_RECHARGE    "RECHG"
#define BUTTON_UNIT_MENU_ACTION_REMOVE      "REMVE"
#define BUTTON_UNIT_MENU_ACTION_REPAIR      "REPAR"
#define BUTTON_UNIT_MENU_ACTION_RELOAD      "RLOAD"
#define BUTTON_UNIT_MENU_ACTION_RESEARCH    "RSRCH"
#define BUTTON_UNIT_MENU_ACTION_SENTRY      "SNTRY"
#define BUTTON_UNIT_MENU_ACTION_START       "START"
#define BUTTON_UNIT_MENU_ACTION_STEAL       "STEAL"
#define BUTTON_UNIT_MENU_ACTION_STOP        "STOP"
#define BUTTON_UNIT_MENU_ACTION_UPGRADE     "UPGRD"
#define BUTTON_UNIT_MENU_ACTION_WAIT        "WAIT"
#define BUTTON_UNIT_MENU_ACTION_XFER        "XFER"
#define BUTTON_UNIT_MENU_ACTION_XFORM       "XFORM"

GIUnitActionMenu::GIUnitActionMenu(vector<UNIT_MENU_ACTION> buttons)
:_delegate_w(NULL)
{}

GIUnitActionMenu::~GIUnitActionMenu()
{}